# Generated by Django 4.0.1 on 2022-01-14 11:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0003_remove_post_photo_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resume',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
